var serviceDirection=new google.maps.DirectionsService,userLocation=new google.maps.LatLng(0,0),restaurants,prizes=[],overmap,markerUser,markersArray=[],testLocFallbackOn=!0,mapthumb={width:"200",height:"100",zoom:"15"},mapDetailZoomLevel=15,mapYOffset=0,mapXOffset=0,mapYzoomOffset=180,mapXzoomOffset=0,bounds=new google.maps.LatLngBounds,loadCt=0,loadMax=0,isMobi=!1,isMobile=!1,maxDistance=3E4,listingCt=0,locationTimer;
function InitApp(){/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)&&(isMobile=!0);$("#btncloseloc").click(function(){_gaq.push(["_trackEvent","Main Nav","location","close"]);$("#locationbox").fadeOut()});$("#btncloseinfo").click(GetHome);$("#loc").click(function(){CloseAllBoxes();$("#locationbox").fadeIn();$("#loctext").focus();return!1});$("#btnclose").click(function(){$("#aboutbox").fadeOut()});$("#info").click(function(){CloseAllBoxes();$("#aboutbox").fadeIn();$(".scroll-pane").jScrollPane({showArrows:!1,
verticalGutter:15})});$("#listshow").click(function(){ListShow()});$("#appmobi").click(function(){_gaq.push(["_trackEvent","Main Nav","app","open"]);$("#appModal").modal("show")});$("#btnlocsearch").click(function(){_gaq.push(["_trackEvent","Main Nav","location search",""]);var a=$("#loctext").val();DebugOut("getting coords for: "+a);(new google.maps.Geocoder).geocode({address:a},function(a,c){c==google.maps.GeocoderStatus.OK?($("#locationbox").fadeOut(),HandleGeolocationQuery({coords:{latitude:a[0].geometry.location.lat(),
longitude:a[0].geometry.location.lng()}})):alert("Could not find address: "+c)})})}function QueryLocation(){window.navigator.geolocation.getCurrentPosition(HandleGeolocationQuery,HandleGeolocationErrors,{enableHighAccuracy:!0,timeout:5E3,maximumAge:0})}function QueryLocationLoop(){window.navigator.geolocation.getCurrentPosition(HandleGeolocationQueryLoop,HandleGeolocationErrorsLoop,{enableHighAccuracy:!0,timeout:5E3,maximumAge:0})}
function UpdateProgressBar(){loadCt++;var a=100*(loadCt/loadMax);DebugOut("loading: "+a+"% ("+loadMax+"/"+loadCt+")");99<a?$("#loader").hide():(66<a?$("#loader .message").html("Measuring distances"):33<a?$("#loader .message").html("Finding restaurants"):$("#loader .message").html("Getting prizes"),$(".progress .bar").css("width",a+"%"))}
function GetRest(){var a="reactor/";isMobi&&(a="http://theprizeinside.com/reactor/");clearOverlays();PlaceUserLocMarker();$("#listlist").empty();$.get(a+"srvlist/getnames",function(a){DebugOut(a);restaurants=isMobi?jQuery.parseJSON(a):a;loadMax=2*restaurants.length;for(idx in restaurants)UpdateProgressBar(),GetDistance(idx)})}
function GetRestMobi(){clearOverlays();$("#listlist").empty();$.get("http://theprizeinside.com/reactor/srvlist/getnames",function(a){DebugOut(a);restaurants=jQuery.parseJSON(a);loadMax=2*restaurants.length;for(idx in restaurants)UpdateProgressBar(),GetDistance(idx)})}
function GetDistance(a){var b={location:userLocation,radius:maxDistance,name:'"'+restaurants[a].restaurantName+'"'};service=new google.maps.places.PlacesService(overmap);service.nearbySearch(b,function(b,d){d==google.maps.places.PlacesServiceStatus.OK&&(DebugOut(b),restaurants[a].locations=b);UpdateProgressBar();DebugOut(restaurants);PlaceMarkers(a);BuildListing(a)})}
function PlaceUserLocMarker(){var a=new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|ff0000",new google.maps.Size(21,34),new google.maps.Point(0,0),new google.maps.Point(10,34));markerUser=new google.maps.Marker({map:overmap,icon:a,position:userLocation,title:"You Are Here",ref:-1})}
function UpdateDistances(){for(idx in restaurants)for(jdx in restaurants[idx].locations)restaurants[idx].locations[jdx].distance=CalcDistance(userLocation.lat(),userLocation.lng(),restaurants[idx].locations[jdx].geometry.location.lat(),restaurants[idx].locations[jdx].geometry.location.lng())}
function PlaceMarkers(a){for(jdx in restaurants[a].locations){restaurants[a].locations[jdx].distance=CalcDistance(userLocation.lat(),userLocation.lng(),restaurants[a].locations[jdx].geometry.location.lat(),restaurants[a].locations[jdx].geometry.location.lng());restaurants[a].locations[jdx].maplink="http://maps.google.com/?saddr="+userLocation.lat()+","+userLocation.lng()+"&daddr="+restaurants[a].locations[jdx].vicinity;restaurants[a].locations[jdx].address=restaurants[a].locations[jdx].vicinity.replace(",",
"<br/>");var b=new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|"+restaurants[a].restaurantColor,new google.maps.Size(21,34),new google.maps.Point(0,0),new google.maps.Point(10,34)),b=new google.maps.Marker({map:overmap,icon:b,position:restaurants[a].locations[jdx].geometry.location,title:restaurants[a].restaurantName+" ("+Math.round(10*restaurants[a].locations[jdx].distance)/10+" mi.)",ref:jdx});markersArray.push(b);google.maps.event.addListener(b,
"click",function(b){_gaq.push(["_trackEvent","Map","markerclick",this.title]);ListHide();overmap.setCenter(this.position);overmap.panBy(mapXzoomOffset,-mapYzoomOffset);infoBubble.setContent(GetDetailContent(a,this.ref));infoBubble.open(overmap,this)});0==jdx&&(restaurants[a].marker=b);if(5<jdx)break}}
function BuildListing(a){DebugOut("building "+restaurants[a].restaurantAlias);DebugOut(restaurants[a].locations);listingCt++;if(void 0!=restaurants[a].locations){var b=$("<li/>").attr("id",restaurants[a].restaurantAlias).attr("listpos",a).attr("distance",restaurants[a].locations[0].distance).addClass("listing"),c="";for(jdx=0;jdx<restaurants[a].prize.length;jdx++)0<jdx&&(c+=" / "),c+=restaurants[a].prize[jdx].prizeName;b.append($("<a/>").attr("href","#").addClass("restaurant").append($("<img/>").attr("src",
"img/marker_legend.png").addClass("marker").css("backgroundColor","#"+restaurants[a].restaurantColor)).append(restaurants[a].restaurantName+" - "+c).click(function(){_gaq.push(["_trackEvent","List","itemclick",restaurants[a].restaurantAlias]);ListHide();overmap.setCenter(restaurants[a].locations[0].geometry.location);overmap.panBy(mapXzoomOffset,-mapYzoomOffset);infoBubble.setContent(GetDetailContent(a,0));infoBubble.open(overmap,restaurants[a].marker);return!1}));$("#listlist").append(b);b=$("#listlist li").get();
b.sort(function(a,b){var c=parseFloat($(a).attr("distance")),d=parseFloat($(b).attr("distance"));return c<d?-1:c>d?1:0});var d=$("#listlist");$.each(b,function(a,b){d.append(b)})}bounds.extend(userLocation);DebugOut("CHECKING FOR FINAL PREP - "+listingCt+" : "+restaurants.length);if(listingCt==restaurants.length){DebugOut("DOING FINAL PREP");b=$("#listlist li").get();for(idx=0;3>idx;idx++)bounds.extend(restaurants[$(b[idx]).attr("listpos")].locations[0].geometry.location);$("#listlist li:eq(0)").before($("<li><h3>Closest</h3></li>")).after($("<li><h3>Nearby</h3></li>"));
$("#listlist").prepend($("<li/>").append($("<div/>").attr("id","listhead").append($("<h2/>").html("Prizes")).append($("<a/>").attr("href","#").attr("onclick","return false;").click(ListHide).append($("<img/>").attr("src","img/listshow.png")))));overmap.fitBounds(bounds);overmap.panBy(mapXOffset,mapYOffset)}}
function CalcRoute(a,b,c){a={origin:userLocation.lat()+","+userLocation.lng(),destination:a,travelMode:google.maps.TravelMode.DRIVING};serviceDirection.route(a,function(a,c){DebugOut(a);c==google.maps.DirectionsStatus.OK&&restaurants[b].prize[0].prizeName&&(restaurants[b].location=new google.maps.LatLng(a.routes[0].legs[0].end_location.lat(),a.routes[0].legs[0].end_location.lng()),restaurants[b].distance=a.routes[0].legs[0].distance.text,restaurants[b].address=a.routes[0].legs[0].end_address.replace(",",
"<br/>"))})}function clearOverlays(){listingCt=0;bounds=new google.maps.LatLngBounds;for(var a=0;a<markersArray.length;a++)markersArray[a].setMap(null);markerUser&&markerUser.setMap(null)}
function GetDetailContent(a,b){var c="";for(idx=0;idx<restaurants[a].prize.length;idx++)0<idx&&(c+=" / "),c+=restaurants[a].prize[idx].prizeName;$("#infobox .prize").html(c);$("#infobox .restaurant").html(restaurants[a].restaurantName);$("#infobox .distance").html(Math.round(10*restaurants[a].locations[b].distance)/10+" mi.");$("#infobox .address").html(restaurants[a].locations[b].address);isMobi?($("#infobox .extlink").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'websitemobi', '"+restaurants[a].restaurantAlias+
"']); AppMobi.device.launchExternal('"+restaurants[a].restaurantUrl+"'); return false;"),$("#infobox .directions").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'directionsmobi', '"+restaurants[a].restaurantAlias+"']); AppMobi.device.launchExternal('"+restaurants[a].locations[b].maplink+"'); return false;")):($("#infobox .extlink").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'website', '"+restaurants[a].restaurantAlias+"']);").attr("href",restaurants[a].restaurantUrl).attr("target",
"_blank"),$("#infobox .directions").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'directions', '"+restaurants[a].restaurantAlias+"']);").addClass("btn").attr("href",restaurants[a].locations[b].maplink).attr("target","_blank"));isMobi?($("#twshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'twsharemobi', '"+restaurants[a].restaurantAlias+"']); twsharemobi(restaurants["+a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;"),$("#fbshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'fbsharemobi', '"+
restaurants[a].restaurantAlias+"']); fbsharemobi(restaurants["+a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;"),$("#gpshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'gpsharemobi', '"+restaurants[a].restaurantAlias+"']); gpsharemobi(restaurants["+a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;")):($("#twshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'twshare', '"+restaurants[a].restaurantAlias+"']); twshare(restaurants["+
a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;"),$("#fbshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'fbshare', '"+restaurants[a].restaurantAlias+"']); fbshare(restaurants["+a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;"),$("#gpshare").attr("onclick","_gaq.push(['_trackEvent', 'Detail', 'gpshare', '"+restaurants[a].restaurantAlias+"']); gpshare(restaurants["+a+"].restaurantName,restaurants["+a+"].prize[0].prizeName); return false;"));
return $("#infobox").html()}function GetHome(){overmap.fitBounds(bounds);overmap.panBy(mapXOffset,mapYOffset);infoBubble.close();return!1}function HandleGeolocationErrors(a){$("#geoModal").fadeIn();_gaq.push(["_trackEvent","Load","location","fail"]);testLocFallbackOn&&(_gaq.push(["_trackEvent","Load","location","setfallback"]),HandleGeolocationQuery({coords:{latitude:40.67857830000001,longitude:-73.5421847}}))}
function HandleGeolocationQuery(a){_gaq.push(["_trackEvent","Load","desktop",""]);1<CalcDistance(userLocation.lat(),userLocation.lng(),a.coords.latitude,a.coords.longitude)?(userLocation=new google.maps.LatLng(a.coords.latitude,a.coords.longitude),DebugOut("user location set: "+a.coords.latitude+", "+a.coords.longitude),$("#location span").html(a.coords.latitude.toString().substring(0,8)+", "+a.coords.longitude.toString().substring(0,8)),GetRest()):alert("User Location Unchanged")}
function HandleGeolocationQueryLoop(a){DebugOut("Distance Change: "+CalcDistance(userLocation.lat(),userLocation.lng(),a.coords.latitude,a.coords.longitude));0.5>CalcDistance(userLocation.lat(),userLocation.lng(),a.coords.latitude,a.coords.longitude)?DebugOut("User Location Minimal Change"):10>CalcDistance(userLocation.lat(),userLocation.lng(),a.coords.latitude,a.coords.longitude)?(DebugOut("User Location Small Change"),userLocation=new google.maps.LatLng(a.coords.latitude,a.coords.longitude),DebugOut("user location set: "+
a.coords.latitude+", "+a.coords.longitude),$("#location span").html(a.coords.latitude.toString().substring(0,8)+", "+a.coords.longitude.toString().substring(0,8)),markerUser.setMap(null),PlaceUserLocMarker(),UpdateDistances()):(DebugOut("User Location Large Change"),userLocation=new google.maps.LatLng(a.coords.latitude,a.coords.longitude),DebugOut("user location set: "+a.coords.latitude+", "+a.coords.longitude),$("#location span").html(a.coords.latitude.toString().substring(0,8)+", "+a.coords.longitude.toString().substring(0,
8)),GetRest())}function HandleGeolocationErrorsLoop(a){DebugOut("User Location Not Available")}
function HandleGeolocationQueryMobi(a){_gaq.push(["_trackEvent","Load","app",""]);1<CalcDistance(userLocation.lat(),userLocation.lng(),a.coords.latitude,a.coords.longitude)&&(userLocation=new google.maps.LatLng(a.coords.latitude,a.coords.longitude),DebugOut("user location set: "+a.coords.latitude+", "+a.coords.longitude),$("#location span").html(a.coords.latitude.toString().substring(0,8)+", "+a.coords.longitude.toString().substring(0,8)),GetRest())}
function InitMap(){var a={zoom:15,center:new google.maps.LatLng(40.6687125,-73.5270709),mapTypeId:google.maps.MapTypeId.ROADMAP,scrollwheel:!0,streetViewControl:!1,disableDefaultUI:!0};overmap=new google.maps.Map(document.getElementById("overmap"),a);infoBubble=new InfoBubble({map:overmap,minWidth:300,minHeight:220,maxWidth:400,maxHeight:220,shadowStyle:0,padding:20,backgroundColor:"#f6f0e7",borderRadius:0,arrowSize:15,borderWidth:2,borderColor:"#362814",disableAutoPan:!0,hideCloseButton:!0,arrowPosition:"50%",
zindex:2E3,backgroundClassName:"float-panel info_box",arrowStyle:0})}function ListHide(){_gaq.push(["_trackEvent","List","hide","header"]);$("#listlist").fadeOut();$("#listshow").fadeIn()}function ListShow(){_gaq.push(["_trackEvent","List","show","listshow"]);GetHome();$("#listlist").fadeIn();$("#listshow").fadeOut()}
function fbshare(a,b){var c="https://www.facebook.com/dialog/feed?app_id=314668331957423&link="+escape(social.link)+"&picture="+escape(social.image)+"&name="+escape(social.title)+"&caption="+escape(social.title)+"&description="+escape("I found the "+b+" at "+a+" thanks to ThePrizeInside")+"&redirect_uri=https://facebook.com/";openpopup(c,"facebook",1E3,450)}
function fbsharemobi(a,b){var c="https://www.facebook.com/dialog/feed?app_id=314668331957423&link="+escape(social.link)+"&picture="+escape(social.image)+"&name="+escape(social.title)+"&caption="+escape(social.title)+"&description="+escape("I found the "+b+" at "+a+" thanks to ThePrizeInside")+"&redirect_uri=https://facebook.com/";AppMobi.device.launchExternal(c)}
function twshare(a,b){DebugOut("twshare");var c="http://twitter.com/home?status=";isMobile&&(c="https://mobile.twitter.com/compose/tweet?status=");var d=escape("I found the "+b+" at "+a+" thanks to ThePrizeInside")+" "+escape(social.link);openpopup(c+d,"tweeters",550,450)}function twsharemobi(a,b){var c="https://mobile.twitter.com/compose/tweet?status="+escape("I found the "+b+" at "+a+" thanks to ThePrizeInside http://theprizeinside.com");AppMobi.device.launchExternal(c)}
function gpshare(a,b){var c="https://plus.google.com/share?url="+escape(social.link)+"&description="+escape("I found the "+b+" at "+a+" thanks to ThePrizeInside");openpopup(c,"gplus",550,450)}function gpsharemobi(a,b){var c="https://plus.google.com/share?url="+escape(social.link)+"&description="+escape("I found the "+b+" at "+a+" thanks to ThePrizeInside");AppMobi.device.launchExternal(c)}function CloseAllBoxes(){$("#geoModal").fadeOut();$("#locationbox").fadeOut();$("#aboutbox").fadeOut()}
Number.prototype.toRad=function(){return this*Math.PI/180};function roundNumber(a,b){var c=Math.pow(10,b);return Math.round(a*c)/c}function CalcDistance(a,b,c,d){var e=(roundNumber(a,7)-roundNumber(c,7)).toRad();b=(roundNumber(b,7)-roundNumber(d,7)).toRad();a=Math.sin(e/2)*Math.sin(e/2)+Math.cos(c.toRad())*Math.cos(a.toRad())*Math.sin(b/2)*Math.sin(b/2);return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}function pausecomp(a){var b=new Date,c=null;do c=new Date;while(c-b<a)}
function DebugOut(a){}function openpopup(a,b,c,d){var e;e="toolbar=0,location=0,height="+d+",width="+c;var f,g;"Microsoft Internet Explorer"==navigator.appName?(g=screen.height,f=screen.width):(g=window.outerHeight,f=window.outerWidth);leftvar=(f-c)/2;rightvar=(g-d)/2;"Microsoft Internet Explorer"==navigator.appName?(c=leftvar,d=rightvar):(c=leftvar-pageXOffset,d=rightvar-pageYOffset);e=e+",left="+c;e=e+",top="+d;window.open(a,b,e)};
